[project]
name = "a1-comp-esc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faker>=37.1.0",
    "plotly>=6.0.1",
    "sqlalchemy>=2.0.40",
    "streamlit>=1.44.1",
    "tqdm>=4.67.1",
]
